### ISSUE TITLE
Can not enter to server

### ISSUE THREAD

**Issue by oscaredmu** [ivanilves/xiringuito#33] opened 2017-05-29 18:59 UTC
I am sure about the password and my Caps status, I am not able to connect due to an endless password request when I try by  ./xiringuito root@myhost.domain.com 10.9.0.0/16

I am trying from Mac to CentOS, please note that tuntap was correctly installed

Edit: It could be nice if we can pass sshkeys by parameter and not via SSH_EXTRA_OPTS

**Comment by ivanilves** [comment] 2017-05-31 16:24
Hi @oscaredmu 

Thank you for informing on this issue!
The problem is that it's not easy to fix the password thing right now.
I plan to do a refactor soon - and make a stable Golang based core,
fully programmable and free of such issues. But it's not that easy. :cry:  

> Edit: It could be nice if we can pass sshkeys by parameter and not via SSH_EXTRA_OPTS

Great proposal! Will do it ASAP. I think this week.

**Comment by ivanilves** [comment] 2017-05-31 16:27
Will you be OK with just having an option to pass specific key?

**Comment by oscaredmu** [comment] 2017-05-31 16:29
@ivanilves ... That would be pretty enough ! Thank you

**Comment by ivanilves** [comment] 2017-05-31 17:04
done @oscaredmu !

Tested manually and with CI - works.

Could you do a peer review to merge it "good" way:
https://github.com/ivanilves/xiringuito/pull/34 
???

**Comment by vonrabbe** [comment] 2017-05-31 17:09
Great update @ivanilves :+1:

**Comment by ivanilves** [comment] 2017-05-31 17:16
Oh, already reviewed by @vonrabbe 
Merged! @oscaredmu pull latest master :wink: 

Thank you all! Closing this issue.

**Comment by oscaredmu** [comment] 2017-05-31 17:17
Tested ... Working fine !

Thank you @ivanilves

**Closed as completed** 2017-05-31 17:17 UTC
Labels: bug

**Comment by ivanilves** [comment] 2017-05-31 17:47
Great to hear it works for you @oscaredmu !

If `xiringuito` works well for you, the one extra thing I may humbly ask you is to give a star to this repository :wink:

**Comment by oscaredmu** [comment] 2017-05-31 17:52
@ivanilves ... This is great for small embedded devices

**Comment by luckypoem** [comment] 2019-11-12 17:36
hi。

i still have the problem:

./xiringuito -p 63785 root@vps-ip 0.0.0.0/0
[ (client) sudo check ] Password:

[ (server) sudo check ] root@vps-ip's password: 

TUNNEL ID: 41 (local: 0)
root@vps-ip's password: 
root@vps-ip's password: 
root@vps-ip's password: 
SERVER: root@vps-ip
root@vps-ip's password: 
Connection timed out during banner exchange

i'm sure i entered the correct pw.but i just can't login.why??
